export const CONNECT_DB_REQUEST = "CONNECT_DB_REQUEST";
export const CONNECT_DB_FAIL = "CONNECT_DB_FAIL";
export const CONNECT_DB_SUCCESS = "CONNECT_DB_SUCCESS";


export const QUERRY_RUN_REQUEST = "QUERRY_RUN_REQUEST";
export const QUERRY_RUN_FAIL = "QUERRY_RUN_FAIL";
export const QUERRY_RUN_SUCCESS = "QUERRY_RUN_SUCCESS";
