export const CONNECT_DB_REQUEST = "CONNECT_DB_REQUEST";
export const CONNECT_DB_FAIL = "CONNECT_DB_FAIL";
export const CONNECT_DB_SUCCESS = "CONNECT_DB_SUCCESS";

export const SYSTEM_QUERY_REQUEST = "SYSTEM_QUERY_REQUEST";
export const SYSTEM_QUERY_SUCCESS = "SYSTEM_QUERY_SUCCESS";
export const SYSTEM_QUERY_FAIL = "SYSTEM_QUERY_FAIL";

export const USER_QUERY_REQUEST = "USER_QUERY_REQUEST";
export const USER_QUERY_SUCCESS = "USER_QUERY_SUCCESS";
export const USER_QUERY_FAIL = "USER_QUERY_FAIL";