export const CONNECT_DB_REQUEST = "CONNECT_DB_REQUEST";
export const CONNECT_DB_FAIL = "CONNECT_DB_FAIL";
export const CONNECT_DB_SUCCESS = "CONNECT_DB_SUCCESS";

export const DISCONNECT_DB_REQUEST = "DISCONNECT_DB_REQUEST";
export const DISCONNECT_DB_FAIL = "DISCONNECT_DB_FAIL";
export const DISCONNECT_DB_SUCCESS = "DISCONNECT_DB_SUCCESS";

export const SYSTEM_QUERY_REQUEST = "SYSTEM_QUERY_REQUEST";
export const SYSTEM_QUERY_SUCCESS = "SYSTEM_QUERY_SUCCESS";
export const SYSTEM_QUERY_FAIL = "SYSTEM_QUERY_FAIL";

export const USER_QUERY_REQUEST = "USER_QUERY_REQUEST";
export const USER_QUERY_SUCCESS = "USER_QUERY_SUCCESS";
export const USER_QUERY_FAIL = "USER_QUERY_FAIL";

export const QUERY_SUGGESTION_REQUEST = "QUERY_SUGGESTION_REQUEST";
export const QUERY_SUGGESTION_SUCCESS = "QUERY_SUGGESTION_SUCCESS";
export const QUERY_SUGGESTION_FAIL = "QUERY_SUGGESTION_FAIL";

export const CHECK_CONNECTION_REQUEST = "CHECK_CONNECTION_REQUEST";
export const CHECK_CONNECTION_SUCCESS = "CHECK_CONNECTION_SUCCESS";
export const CHECK_CONNECTION_FAIL = "CHECK_CONNECTION_FAIL";

